linters:
  enable:
  - gosimple
  - structcheck
  - varcheck
  - errcheck
  - staticcheck
  - ineffassign
  - deadcode
  - typecheck
  - govet
  - unused
  - scopelint
  - goimports
  - prealloc
  - unconvert
